### ISSUE TITLE
Compiling on windows with 15 ea fails:  module not found: jdk.internal.vm.compiler

### ISSUE THREAD

**Issue by Siedlerchr** [AdoptOpenJDK/openjdk15-binaries#1]
Hi,
hope it's the right repo.
LInux and mac work fine in compiling and building the project. However on window it fails 
 with D:\a\***\***\src\main\java\module-info.java:67: error: module not found: jdk.internal.vm.compiler
    requires jdk.internal.vm.compiler;
> Task :compileJava FAILED

See the log for an example 
https://github.com/JabRef/jabref/pull/6748/checks?check_run_id=1009424853

**Comment by karianna** [comment]
15.0.1 has this fixed
